-- Create "departments" table
CREATE TABLE "departments" ("id" bigserial NOT NULL, "title" character varying NOT NULL, "deleted" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"), CONSTRAINT "departments_title_key" UNIQUE ("title"));
-- Create "employees" table
CREATE TABLE "employees" ("id" bigserial NOT NULL, "name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "hash" character varying NOT NULL, "registration_date" timestamptz NOT NULL, "authorization_date" timestamptz NOT NULL, "activate" boolean NOT NULL DEFAULT false, "hidden" boolean NOT NULL DEFAULT false, "department" bigint NULL, "role" character varying NOT NULL DEFAULT 'USER', "deleted" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"), CONSTRAINT "employees_phone_key" UNIQUE ("phone"), CONSTRAINT "employees_department_fkey" FOREIGN KEY ("department") REFERENCES "departments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "categories" table
CREATE TABLE "categories" ("id" bigserial NOT NULL, "title" character varying NOT NULL, "deleted" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"), CONSTRAINT "categories_title_key" UNIQUE ("title"));
-- Create "profiles" table
CREATE TABLE "profiles" ("id" bigserial NOT NULL, "title" character varying NOT NULL, "category" bigint NOT NULL, "deleted" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"), CONSTRAINT "profiles_title_key" UNIQUE ("title"), CONSTRAINT "profiles_category_fkey" FOREIGN KEY ("category") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "equipments" table
CREATE TABLE "equipments" ("id" bigserial NOT NULL, "serial_number" character varying NOT NULL, "profile" bigint NOT NULL, "deleted" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"), CONSTRAINT "equipments_serial_number_key" UNIQUE ("serial_number"), CONSTRAINT "equipments_profile_fkey" FOREIGN KEY ("profile") REFERENCES "profiles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "companies" table
CREATE TABLE "companies" ("id" bigserial NOT NULL, "title" character varying NOT NULL, "deleted" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"), CONSTRAINT "companies_title_key" UNIQUE ("title"));
-- Create "contracts" table
CREATE TABLE "contracts" ("id" bigserial NOT NULL, "number" character varying NOT NULL, "address" character varying NOT NULL, "deleted" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"), CONSTRAINT "contracts_number_key" UNIQUE ("number"));
-- Create "locations" table
CREATE TABLE "locations" ("id" bigserial NOT NULL, "date" timestamptz NOT NULL, "code" character varying NOT NULL, "equipment" bigint NOT NULL, "employee" bigint NOT NULL, "company" bigint NOT NULL, "from_department" bigint NULL, "from_employee" bigint NULL, "from_contract" bigint NULL, "to_department" bigint NULL, "to_employee" bigint NULL, "to_contract" bigint NULL, "transfer_type" character varying NULL, "price" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "locations_company_fkey" FOREIGN KEY ("company") REFERENCES "companies" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_employee_fkey" FOREIGN KEY ("employee") REFERENCES "employees" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_equipment_fkey" FOREIGN KEY ("equipment") REFERENCES "equipments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_from_contract_fkey" FOREIGN KEY ("from_contract") REFERENCES "contracts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_from_department_fkey" FOREIGN KEY ("from_department") REFERENCES "departments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_from_employee_fkey" FOREIGN KEY ("from_employee") REFERENCES "employees" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_to_contract_fkey" FOREIGN KEY ("to_contract") REFERENCES "contracts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_to_department_fkey" FOREIGN KEY ("to_department") REFERENCES "departments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "locations_to_employee_fkey" FOREIGN KEY ("to_employee") REFERENCES "employees" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "replaces" table
CREATE TABLE "replaces" ("id" bigserial NOT NULL, "transfer_from" bigint NOT NULL, "transfer_to" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "replaces_transfer_from_fkey" FOREIGN KEY ("transfer_from") REFERENCES "locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "replaces_transfer_to_fkey" FOREIGN KEY ("transfer_to") REFERENCES "locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
