// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (title)
VALUES ($1)
RETURNING id, title, deleted_at
`

func (q *Queries) CreateCategory(ctx context.Context, title string) (*Category, error) {
	row := q.db.QueryRow(ctx, createCategory, title)
	var i Category
	err := row.Scan(&i.ID, &i.Title, &i.DeletedAt)
	return &i, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
UPDATE categories
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCategory, id)
}

const listCategory = `-- name: ListCategory :many
SELECT id, title, deleted_at, count(*) OVER () AS total
FROM categories
WHERE ($1::bool = true OR deleted_at IS NULL)
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
  AND (array_length($3::bigint[], 1) IS NULL OR id = ANY ($3))
ORDER BY CASE WHEN $4::text = 'id' AND $5::text = 'asc' THEN id::text END,
         CASE WHEN $4 = 'id' AND $5 = 'desc' THEN id::text END DESC,
         CASE WHEN $4 = 'title' AND $5 = 'asc' THEN title END,
         CASE WHEN $4 = 'title' AND $5 = 'desc' THEN title END DESC
LIMIT $7 OFFSET $6
`

type ListCategoryParams struct {
	WithDeleted      bool    `db:"with_deleted" json:"with_deleted"`
	Search           string  `db:"search" json:"search"`
	Ids              []int64 `db:"ids" json:"ids"`
	SortColumn       string  `db:"sort_column" json:"sort_column"`
	SortOrder        string  `db:"sort_order" json:"sort_order"`
	PaginationOffset int32   `db:"pagination_offset" json:"pagination_offset"`
	PaginationLimit  int32   `db:"pagination_limit" json:"pagination_limit"`
}

type ListCategoryRow struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Total     int64              `db:"total" json:"total"`
}

func (q *Queries) ListCategory(ctx context.Context, arg *ListCategoryParams) ([]*ListCategoryRow, error) {
	rows, err := q.db.Query(ctx, listCategory,
		arg.WithDeleted,
		arg.Search,
		arg.Ids,
		arg.SortColumn,
		arg.SortOrder,
		arg.PaginationOffset,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCategoryRow
	for rows.Next() {
		var i ListCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DeletedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCategory = `-- name: ReadCategory :one
SELECT id, title, deleted_at
FROM categories
WHERE id = $1
`

func (q *Queries) ReadCategory(ctx context.Context, id int64) (*Category, error) {
	row := q.db.QueryRow(ctx, readCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Title, &i.DeletedAt)
	return &i, err
}

const restoreCategory = `-- name: RestoreCategory :execresult
UPDATE categories
SET deleted_at = NULL
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreCategory(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, restoreCategory, id)
}

const updateCategory = `-- name: UpdateCategory :execresult
UPDATE categories
SET title = $1
WHERE id = $2
  AND title != $1
`

type UpdateCategoryParams struct {
	Title string `db:"title" json:"title"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg *UpdateCategoryParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateCategory, arg.Title, arg.ID)
}
