// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (title)
VALUES ($1)
RETURNING id, title, deleted_at
`

func (q *Queries) CreateCompany(ctx context.Context, title string) (*Company, error) {
	row := q.db.QueryRow(ctx, createCompany, title)
	var i Company
	err := row.Scan(&i.ID, &i.Title, &i.DeletedAt)
	return &i, err
}

const deleteCompany = `-- name: DeleteCompany :execresult
UPDATE companies
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteCompany(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCompany, id)
}

const listCompany = `-- name: ListCompany :many
SELECT id, title, deleted_at, count(*) OVER () AS total
FROM companies
WHERE ($1::bool = true OR deleted_at IS NULL)
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
  AND (array_length($3::bigint[], 1) IS NULL OR id = ANY ($3))
ORDER BY CASE WHEN $4::text = 'id' AND $5::text = 'asc' THEN id::text END,
         CASE WHEN $4 = 'id' AND $5 = 'desc' THEN id::text END DESC,
         CASE WHEN $4 = 'title' AND $5 = 'asc' THEN title END,
         CASE WHEN $4 = 'title' AND $5 = 'desc' THEN title END DESC
LIMIT $7 OFFSET $6
`

type ListCompanyParams struct {
	WithDeleted      bool    `db:"with_deleted" json:"with_deleted"`
	Search           string  `db:"search" json:"search"`
	Ids              []int64 `db:"ids" json:"ids"`
	SortColumn       string  `db:"sort_column" json:"sort_column"`
	SortOrder        string  `db:"sort_order" json:"sort_order"`
	PaginationOffset int32   `db:"pagination_offset" json:"pagination_offset"`
	PaginationLimit  int32   `db:"pagination_limit" json:"pagination_limit"`
}

type ListCompanyRow struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Total     int64              `db:"total" json:"total"`
}

func (q *Queries) ListCompany(ctx context.Context, arg *ListCompanyParams) ([]*ListCompanyRow, error) {
	rows, err := q.db.Query(ctx, listCompany,
		arg.WithDeleted,
		arg.Search,
		arg.Ids,
		arg.SortColumn,
		arg.SortOrder,
		arg.PaginationOffset,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCompanyRow
	for rows.Next() {
		var i ListCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DeletedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCompany = `-- name: ReadCompany :one
SELECT id, title, deleted_at
FROM companies
WHERE id = $1
`

func (q *Queries) ReadCompany(ctx context.Context, id int64) (*Company, error) {
	row := q.db.QueryRow(ctx, readCompany, id)
	var i Company
	err := row.Scan(&i.ID, &i.Title, &i.DeletedAt)
	return &i, err
}

const restoreCompany = `-- name: RestoreCompany :execresult
UPDATE companies
SET deleted_at = NULL
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreCompany(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, restoreCompany, id)
}

const updateCompany = `-- name: UpdateCompany :execresult
UPDATE companies
SET title = $1
WHERE id = $2
  AND title != $1
`

type UpdateCompanyParams struct {
	Title string `db:"title" json:"title"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg *UpdateCompanyParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateCompany, arg.Title, arg.ID)
}
