// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContract = `-- name: CreateContract :one
INSERT INTO contracts (number, address)
VALUES ($1, $2)
RETURNING id, number, address, deleted_at
`

type CreateContractParams struct {
	Number  string `db:"number" json:"number"`
	Address string `db:"address" json:"address"`
}

func (q *Queries) CreateContract(ctx context.Context, arg *CreateContractParams) (*Contract, error) {
	row := q.db.QueryRow(ctx, createContract, arg.Number, arg.Address)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Address,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteContract = `-- name: DeleteContract :execresult
UPDATE contracts
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteContract(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteContract, id)
}

const listContract = `-- name: ListContract :many
SELECT id, number, address, deleted_at, count(*) OVER () AS total
FROM contracts
WHERE ($1::bool = true OR deleted_at IS NULL)
  AND ($2::text = '' OR (number || ' ' || address) ILIKE '%' || $2 || '%')
  AND (array_length($3::bigint[], 1) IS NULL OR id = ANY ($3))
ORDER BY CASE WHEN $4::text = 'id' AND $5::text = 'asc' THEN id::text END,
         CASE WHEN $4 = 'id' AND $5 = 'desc' THEN id::text END DESC,
         CASE WHEN $4 = 'number' AND $5 = 'asc' THEN number END,
         CASE WHEN $4 = 'number' AND $5 = 'desc' THEN number END DESC,
         CASE WHEN $4 = 'address' AND $5 = 'asc' THEN address END,
         CASE WHEN $4 = 'address' AND $5 = 'desc' THEN address END DESC
LIMIT $7 OFFSET $6
`

type ListContractParams struct {
	WithDeleted      bool    `db:"with_deleted" json:"with_deleted"`
	Search           string  `db:"search" json:"search"`
	Ids              []int64 `db:"ids" json:"ids"`
	SortColumn       string  `db:"sort_column" json:"sort_column"`
	SortOrder        string  `db:"sort_order" json:"sort_order"`
	PaginationOffset int32   `db:"pagination_offset" json:"pagination_offset"`
	PaginationLimit  int32   `db:"pagination_limit" json:"pagination_limit"`
}

type ListContractRow struct {
	ID        int64              `db:"id" json:"id"`
	Number    string             `db:"number" json:"number"`
	Address   string             `db:"address" json:"address"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Total     int64              `db:"total" json:"total"`
}

func (q *Queries) ListContract(ctx context.Context, arg *ListContractParams) ([]*ListContractRow, error) {
	rows, err := q.db.Query(ctx, listContract,
		arg.WithDeleted,
		arg.Search,
		arg.Ids,
		arg.SortColumn,
		arg.SortOrder,
		arg.PaginationOffset,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListContractRow
	for rows.Next() {
		var i ListContractRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Address,
			&i.DeletedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readContract = `-- name: ReadContract :one
SELECT id, number, address, deleted_at
FROM contracts
WHERE id = $1
`

func (q *Queries) ReadContract(ctx context.Context, id int64) (*Contract, error) {
	row := q.db.QueryRow(ctx, readContract, id)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Address,
		&i.DeletedAt,
	)
	return &i, err
}

const restoreContract = `-- name: RestoreContract :execresult
UPDATE contracts
SET deleted_at = NULL
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreContract(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, restoreContract, id)
}

const updateContract = `-- name: UpdateContract :execresult
UPDATE contracts
SET number  = $1,
    address = $2
WHERE id = $3
  AND (number != $1 OR address != $2)
`

type UpdateContractParams struct {
	Number  string `db:"number" json:"number"`
	Address string `db:"address" json:"address"`
	ID      int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateContract(ctx context.Context, arg *UpdateContractParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateContract, arg.Number, arg.Address, arg.ID)
}
