// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: department.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (title)
VALUES ($1)
RETURNING id, title, deleted_at
`

func (q *Queries) CreateDepartment(ctx context.Context, title string) (*Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, title)
	var i Department
	err := row.Scan(&i.ID, &i.Title, &i.DeletedAt)
	return &i, err
}

const deleteDepartment = `-- name: DeleteDepartment :execresult
UPDATE departments
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteDepartment(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteDepartment, id)
}

const listDepartment = `-- name: ListDepartment :many
SELECT id, title, deleted_at, count(*) OVER () AS total
FROM departments
WHERE ($1::bool = true OR deleted_at IS NULL)
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
  AND (array_length($3::bigint[], 1) IS NULL OR id = ANY ($3))
ORDER BY CASE WHEN $4::text = 'id' AND $5::text = 'asc' THEN id::text END,
         CASE WHEN $4 = 'id' AND $5 = 'desc' THEN id::text END DESC,
         CASE WHEN $4 = 'title' AND $5 = 'asc' THEN title END,
         CASE WHEN $4 = 'title' AND $5 = 'desc' THEN title END DESC
LIMIT $7 OFFSET $6
`

type ListDepartmentParams struct {
	WithDeleted      bool    `db:"with_deleted" json:"with_deleted"`
	Search           string  `db:"search" json:"search"`
	Ids              []int64 `db:"ids" json:"ids"`
	SortColumn       string  `db:"sort_column" json:"sort_column"`
	SortOrder        string  `db:"sort_order" json:"sort_order"`
	PaginationOffset int32   `db:"pagination_offset" json:"pagination_offset"`
	PaginationLimit  int32   `db:"pagination_limit" json:"pagination_limit"`
}

type ListDepartmentRow struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Total     int64              `db:"total" json:"total"`
}

func (q *Queries) ListDepartment(ctx context.Context, arg *ListDepartmentParams) ([]*ListDepartmentRow, error) {
	rows, err := q.db.Query(ctx, listDepartment,
		arg.WithDeleted,
		arg.Search,
		arg.Ids,
		arg.SortColumn,
		arg.SortOrder,
		arg.PaginationOffset,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListDepartmentRow
	for rows.Next() {
		var i ListDepartmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DeletedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readDepartment = `-- name: ReadDepartment :one
SELECT id, title, deleted_at
FROM departments
WHERE id = $1
`

func (q *Queries) ReadDepartment(ctx context.Context, id int64) (*Department, error) {
	row := q.db.QueryRow(ctx, readDepartment, id)
	var i Department
	err := row.Scan(&i.ID, &i.Title, &i.DeletedAt)
	return &i, err
}

const restoreDepartment = `-- name: RestoreDepartment :execresult
UPDATE departments
SET deleted_at = NULL
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreDepartment(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, restoreDepartment, id)
}

const updateDepartment = `-- name: UpdateDepartment :execresult
UPDATE departments
SET title = $1
WHERE id = $2
  AND title != $1
`

type UpdateDepartmentParams struct {
	Title string `db:"title" json:"title"`
	ID    int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg *UpdateDepartmentParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateDepartment, arg.Title, arg.ID)
}
