// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (last_name, first_name, middle_name, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, last_name, first_name, middle_name, phone, department_id, deleted_at
`

type CreateEmployeeParams struct {
	LastName   string `db:"last_name" json:"last_name"`
	FirstName  string `db:"first_name" json:"first_name"`
	MiddleName string `db:"middle_name" json:"middle_name"`
	Phone      string `db:"phone" json:"phone"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg *CreateEmployeeParams) (*Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Phone,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Phone,
		&i.DepartmentID,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteEmployee = `-- name: DeleteEmployee :execresult
UPDATE employees
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteEmployee, id)
}

const listEmployee = `-- name: ListEmployee :many
SELECT e.id,
       e.last_name,
       e.first_name,
       e.middle_name,
       e.phone,
       e.deleted_at,
       d.id             as department_id,
       d.title          as department_title,
       COUNT(*) OVER () AS total
FROM employees e
         LEFT JOIN public.departments d ON d.id = e.department_id
WHERE ($1::bool = true OR e.deleted_at IS NULL)
  AND ($2::text = '' OR
       (e.last_name || ' ' || e.first_name || ' ' || e.middle_name || ' ' || e.phone || ' ' || d.title) ILIKE
       '%' || $2 || '%')
  AND (array_length($3::bigint[], 1) IS NULL OR e.id = ANY ($3))
ORDER BY CASE WHEN $4::text = 'id' AND $5::text = 'asc' THEN e.id::text END,
         CASE WHEN $4 = 'id' AND $5 = 'desc' THEN e.id::text END DESC,
         CASE WHEN $4 = 'last_name' AND $5 = 'asc' THEN e.last_name END,
         CASE WHEN $4 = 'last_name' AND $5 = 'desc' THEN e.last_name END DESC,
         CASE WHEN $4 = 'first_name' AND $5 = 'asc' THEN e.first_name END,
         CASE WHEN $4 = 'first_name' AND $5 = 'desc' THEN e.first_name END DESC,
         CASE WHEN $4 = 'middle_name' AND $5 = 'asc' THEN e.middle_name END,
         CASE WHEN $4 = 'middle_name' AND $5 = 'desc' THEN e.middle_name END DESC,
         CASE WHEN $4 = 'phone' AND $5 = 'asc' THEN e.phone END,
         CASE WHEN $4 = 'phone' AND $5 = 'desc' THEN e.phone END DESC,
         CASE WHEN $4 = 'department_title' AND $5 = 'asc' THEN d.title END,
         CASE WHEN $4 = 'department_title' AND $5 = 'desc' THEN d.title END DESC
LIMIT $7 OFFSET $6
`

type ListEmployeeParams struct {
	WithDeleted      bool    `db:"with_deleted" json:"with_deleted"`
	Search           string  `db:"search" json:"search"`
	Ids              []int64 `db:"ids" json:"ids"`
	SortColumn       string  `db:"sort_column" json:"sort_column"`
	SortOrder        string  `db:"sort_order" json:"sort_order"`
	PaginationOffset int32   `db:"pagination_offset" json:"pagination_offset"`
	PaginationLimit  int32   `db:"pagination_limit" json:"pagination_limit"`
}

type ListEmployeeRow struct {
	ID              int64              `db:"id" json:"id"`
	LastName        string             `db:"last_name" json:"last_name"`
	FirstName       string             `db:"first_name" json:"first_name"`
	MiddleName      string             `db:"middle_name" json:"middle_name"`
	Phone           string             `db:"phone" json:"phone"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DepartmentID    pgtype.Int8        `db:"department_id" json:"department_id"`
	DepartmentTitle pgtype.Text        `db:"department_title" json:"department_title"`
	Total           int64              `db:"total" json:"total"`
}

func (q *Queries) ListEmployee(ctx context.Context, arg *ListEmployeeParams) ([]*ListEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listEmployee,
		arg.WithDeleted,
		arg.Search,
		arg.Ids,
		arg.SortColumn,
		arg.SortOrder,
		arg.PaginationOffset,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListEmployeeRow
	for rows.Next() {
		var i ListEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.Phone,
			&i.DeletedAt,
			&i.DepartmentID,
			&i.DepartmentTitle,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readEmployee = `-- name: ReadEmployee :one
SELECT e.id,
       e.last_name,
       e.first_name,
       e.middle_name,
       e.phone,
       e.deleted_at,
       d.id    as department_id,
       d.title as department_title
FROM employees e
         LEFT JOIN departments d ON d.id = e.department_id
WHERE e.id = $1
`

type ReadEmployeeRow struct {
	ID              int64              `db:"id" json:"id"`
	LastName        string             `db:"last_name" json:"last_name"`
	FirstName       string             `db:"first_name" json:"first_name"`
	MiddleName      string             `db:"middle_name" json:"middle_name"`
	Phone           string             `db:"phone" json:"phone"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DepartmentID    pgtype.Int8        `db:"department_id" json:"department_id"`
	DepartmentTitle pgtype.Text        `db:"department_title" json:"department_title"`
}

func (q *Queries) ReadEmployee(ctx context.Context, id int64) (*ReadEmployeeRow, error) {
	row := q.db.QueryRow(ctx, readEmployee, id)
	var i ReadEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Phone,
		&i.DeletedAt,
		&i.DepartmentID,
		&i.DepartmentTitle,
	)
	return &i, err
}

const restoreEmployee = `-- name: RestoreEmployee :execresult
UPDATE employees
SET deleted_at = NULL
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreEmployee(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, restoreEmployee, id)
}

const setDepartmentEmployee = `-- name: SetDepartmentEmployee :execresult
UPDATE employees
SET department_id = $1
WHERE id = $2
`

type SetDepartmentEmployeeParams struct {
	DepartmentID pgtype.Int8 `db:"department_id" json:"department_id"`
	ID           int64       `db:"id" json:"id"`
}

func (q *Queries) SetDepartmentEmployee(ctx context.Context, arg *SetDepartmentEmployeeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setDepartmentEmployee, arg.DepartmentID, arg.ID)
}

const updateEmployee = `-- name: UpdateEmployee :execresult
UPDATE employees
SET last_name   = $1,
    first_name  = $2,
    middle_name = $3,
    phone       = $4
WHERE id = $5
  AND (last_name != $1 OR first_name != $2 OR middle_name != $3 OR phone != $4)
`

type UpdateEmployeeParams struct {
	LastName   string `db:"last_name" json:"last_name"`
	FirstName  string `db:"first_name" json:"first_name"`
	MiddleName string `db:"middle_name" json:"middle_name"`
	Phone      string `db:"phone" json:"phone"`
	ID         int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg *UpdateEmployeeParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateEmployee,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Phone,
		arg.ID,
	)
}
