// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Company struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Contract struct {
	ID        int64              `db:"id" json:"id"`
	Number    string             `db:"number" json:"number"`
	Address   string             `db:"address" json:"address"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Department struct {
	ID        int64              `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Employee struct {
	ID           int64              `db:"id" json:"id"`
	LastName     string             `db:"last_name" json:"last_name"`
	FirstName    string             `db:"first_name" json:"first_name"`
	MiddleName   string             `db:"middle_name" json:"middle_name"`
	Phone        string             `db:"phone" json:"phone"`
	DepartmentID pgtype.Int8        `db:"department_id" json:"department_id"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Equipment struct {
	ID           int64              `db:"id" json:"id"`
	SerialNumber string             `db:"serial_number" json:"serial_number"`
	ProfileID    int64              `db:"profile_id" json:"profile_id"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Location struct {
	ID               int64              `db:"id" json:"id"`
	EquipmentID      int64              `db:"equipment_id" json:"equipment_id"`
	EmployeeID       int64              `db:"employee_id" json:"employee_id"`
	CompanyID        int64              `db:"company_id" json:"company_id"`
	MoveAt           pgtype.Timestamptz `db:"move_at" json:"move_at"`
	MoveCode         string             `db:"move_code" json:"move_code"`
	MoveType         pgtype.Text        `db:"move_type" json:"move_type"`
	Price            pgtype.Text        `db:"price" json:"price"`
	FromDepartmentID pgtype.Int8        `db:"from_department_id" json:"from_department_id"`
	FromEmployeeID   pgtype.Int8        `db:"from_employee_id" json:"from_employee_id"`
	FromContractID   pgtype.Int8        `db:"from_contract_id" json:"from_contract_id"`
	ToDepartmentID   pgtype.Int8        `db:"to_department_id" json:"to_department_id"`
	ToEmployeeID     pgtype.Int8        `db:"to_employee_id" json:"to_employee_id"`
	ToContractID     pgtype.Int8        `db:"to_contract_id" json:"to_contract_id"`
	Comment          pgtype.Text        `db:"comment" json:"comment"`
}

type Profile struct {
	ID         int64              `db:"id" json:"id"`
	Title      string             `db:"title" json:"title"`
	CategoryID int64              `db:"category_id" json:"category_id"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Replace struct {
	ID        int64 `db:"id" json:"id"`
	MoveInID  int64 `db:"move_in_id" json:"move_in_id"`
	MoveOutID int64 `db:"move_out_id" json:"move_out_id"`
}

type User struct {
	ID           int64              `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Email        string             `db:"email" json:"email"`
	Role         int32              `db:"role" json:"role"`
	Enabled      bool               `db:"enabled" json:"enabled"`
	LastLoginAt  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	EmployeeID   pgtype.Int8        `db:"employee_id" json:"employee_id"`
}
