// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (title, category_id)
VALUES ($1, $2)
RETURNING id, title, category_id, deleted_at
`

type CreateProfileParams struct {
	Title      string `db:"title" json:"title"`
	CategoryID int64  `db:"category_id" json:"category_id"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg *CreateProfileParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.Title, arg.CategoryID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteProfile = `-- name: DeleteProfile :execresult
UPDATE profiles
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteProfile(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteProfile, id)
}

const listProfile = `-- name: ListProfile :many
SELECT p.id,
       p.title,
       p.deleted_at,
       c.id             as category_id,
       c.title          as category_title,
       COUNT(*) OVER () AS total
FROM profiles p
         INNER JOIN categories c ON c.id = p.category_id
WHERE ($1::bool = true OR p.deleted_at IS NULL)
  AND ($2::text = '' OR (p.title || ' ' || c.title) ILIKE '%' || $2 || '%')
  AND (array_length($3::bigint[], 1) IS NULL OR p.id = ANY ($3))
ORDER BY CASE WHEN $4::text = 'id' AND $5::text = 'asc' THEN p.id::text END,
         CASE WHEN $4 = 'id' AND $5 = 'desc' THEN p.id::text END DESC,
         CASE WHEN $4 = 'title' AND $5 = 'asc' THEN p.title END,
         CASE WHEN $4 = 'title' AND $5 = 'desc' THEN p.title END DESC,
         CASE WHEN $4 = 'category_title' AND $5 = 'asc' THEN c.title END,
         CASE WHEN $4 = 'category_title' AND $5 = 'desc' THEN c.title END DESC
LIMIT $7 OFFSET $6
`

type ListProfileParams struct {
	WithDeleted      bool    `db:"with_deleted" json:"with_deleted"`
	Search           string  `db:"search" json:"search"`
	Ids              []int64 `db:"ids" json:"ids"`
	SortColumn       string  `db:"sort_column" json:"sort_column"`
	SortOrder        string  `db:"sort_order" json:"sort_order"`
	PaginationOffset int32   `db:"pagination_offset" json:"pagination_offset"`
	PaginationLimit  int32   `db:"pagination_limit" json:"pagination_limit"`
}

type ListProfileRow struct {
	ID            int64              `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CategoryID    int64              `db:"category_id" json:"category_id"`
	CategoryTitle string             `db:"category_title" json:"category_title"`
	Total         int64              `db:"total" json:"total"`
}

func (q *Queries) ListProfile(ctx context.Context, arg *ListProfileParams) ([]*ListProfileRow, error) {
	rows, err := q.db.Query(ctx, listProfile,
		arg.WithDeleted,
		arg.Search,
		arg.Ids,
		arg.SortColumn,
		arg.SortOrder,
		arg.PaginationOffset,
		arg.PaginationLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListProfileRow
	for rows.Next() {
		var i ListProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DeletedAt,
			&i.CategoryID,
			&i.CategoryTitle,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readProfile = `-- name: ReadProfile :one
SELECT p.id,
       p.title,
       p.deleted_at,
       c.id    as category_id,
       c.title as category_title
FROM profiles p
         INNER JOIN categories c ON c.id = p.category_id
WHERE p.id = $1
`

type ReadProfileRow struct {
	ID            int64              `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CategoryID    int64              `db:"category_id" json:"category_id"`
	CategoryTitle string             `db:"category_title" json:"category_title"`
}

func (q *Queries) ReadProfile(ctx context.Context, id int64) (*ReadProfileRow, error) {
	row := q.db.QueryRow(ctx, readProfile, id)
	var i ReadProfileRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DeletedAt,
		&i.CategoryID,
		&i.CategoryTitle,
	)
	return &i, err
}

const restoreProfile = `-- name: RestoreProfile :execresult
UPDATE profiles
SET deleted_at = NULL
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreProfile(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, restoreProfile, id)
}

const updateProfile = `-- name: UpdateProfile :execresult
UPDATE profiles
SET title       = $1,
    category_id = $2
WHERE id = $3
  AND (title != $1 OR category_id != $2)
`

type UpdateProfileParams struct {
	Title      string `db:"title" json:"title"`
	CategoryID int64  `db:"category_id" json:"category_id"`
	ID         int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg *UpdateProfileParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateProfile, arg.Title, arg.CategoryID, arg.ID)
}
