// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CreateCategory(ctx context.Context, title string) (*Category, error)
	CreateCompany(ctx context.Context, title string) (*Company, error)
	CreateContract(ctx context.Context, arg *CreateContractParams) (*Contract, error)
	CreateDepartment(ctx context.Context, title string) (*Department, error)
	CreateEmployee(ctx context.Context, arg *CreateEmployeeParams) (*Employee, error)
	CreateEquipment(ctx context.Context, arg *CreateEquipmentParams) (*Equipment, error)
	CreateProfile(ctx context.Context, arg *CreateProfileParams) (*Profile, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteCategory(ctx context.Context, id int64) (pgconn.CommandTag, error)
	DeleteCompany(ctx context.Context, id int64) (pgconn.CommandTag, error)
	DeleteContract(ctx context.Context, id int64) (pgconn.CommandTag, error)
	DeleteDepartment(ctx context.Context, id int64) (pgconn.CommandTag, error)
	DeleteEmployee(ctx context.Context, id int64) (pgconn.CommandTag, error)
	DeleteEquipment(ctx context.Context, id int64) (pgconn.CommandTag, error)
	DeleteProfile(ctx context.Context, id int64) (pgconn.CommandTag, error)
	DeleteUser(ctx context.Context, id int64) (pgconn.CommandTag, error)
	GetByUsernameUser(ctx context.Context, id string) (*GetByUsernameUserRow, error)
	GetPasswordHashUser(ctx context.Context, id int64) (string, error)
	ListCategory(ctx context.Context, arg *ListCategoryParams) ([]*ListCategoryRow, error)
	ListCompany(ctx context.Context, arg *ListCompanyParams) ([]*ListCompanyRow, error)
	ListContract(ctx context.Context, arg *ListContractParams) ([]*ListContractRow, error)
	ListDepartment(ctx context.Context, arg *ListDepartmentParams) ([]*ListDepartmentRow, error)
	ListEmployee(ctx context.Context, arg *ListEmployeeParams) ([]*ListEmployeeRow, error)
	ListEquipment(ctx context.Context, arg *ListEquipmentParams) ([]*ListEquipmentRow, error)
	ListProfile(ctx context.Context, arg *ListProfileParams) ([]*ListProfileRow, error)
	ListUser(ctx context.Context) ([]*ListUserRow, error)
	ReadCategory(ctx context.Context, id int64) (*Category, error)
	ReadCompany(ctx context.Context, id int64) (*Company, error)
	ReadContract(ctx context.Context, id int64) (*Contract, error)
	ReadDepartment(ctx context.Context, id int64) (*Department, error)
	ReadEmployee(ctx context.Context, id int64) (*ReadEmployeeRow, error)
	ReadEquipment(ctx context.Context, id int64) (*ReadEquipmentRow, error)
	ReadProfile(ctx context.Context, id int64) (*ReadProfileRow, error)
	ReadUser(ctx context.Context, id int64) (*ReadUserRow, error)
	RestoreCategory(ctx context.Context, id int64) (pgconn.CommandTag, error)
	RestoreCompany(ctx context.Context, id int64) (pgconn.CommandTag, error)
	RestoreContract(ctx context.Context, id int64) (pgconn.CommandTag, error)
	RestoreDepartment(ctx context.Context, id int64) (pgconn.CommandTag, error)
	RestoreEmployee(ctx context.Context, id int64) (pgconn.CommandTag, error)
	RestoreEquipment(ctx context.Context, id int64) (pgconn.CommandTag, error)
	RestoreProfile(ctx context.Context, id int64) (pgconn.CommandTag, error)
	SetDepartmentEmployee(ctx context.Context, arg *SetDepartmentEmployeeParams) (pgconn.CommandTag, error)
	SetEmployeeUser(ctx context.Context, arg *SetEmployeeUserParams) (pgconn.CommandTag, error)
	SetEnabledUser(ctx context.Context, arg *SetEnabledUserParams) (pgconn.CommandTag, error)
	SetLastLoginAtUser(ctx context.Context, id int64) (pgconn.CommandTag, error)
	SetPasswordHashUser(ctx context.Context, arg *SetPasswordHashUserParams) (pgconn.CommandTag, error)
	SetRoleUser(ctx context.Context, arg *SetRoleUserParams) (pgconn.CommandTag, error)
	UpdateCategory(ctx context.Context, arg *UpdateCategoryParams) (pgconn.CommandTag, error)
	UpdateCompany(ctx context.Context, arg *UpdateCompanyParams) (pgconn.CommandTag, error)
	UpdateContract(ctx context.Context, arg *UpdateContractParams) (pgconn.CommandTag, error)
	UpdateDepartment(ctx context.Context, arg *UpdateDepartmentParams) (pgconn.CommandTag, error)
	UpdateEmployee(ctx context.Context, arg *UpdateEmployeeParams) (pgconn.CommandTag, error)
	UpdateEquipment(ctx context.Context, arg *UpdateEquipmentParams) (pgconn.CommandTag, error)
	UpdateProfile(ctx context.Context, arg *UpdateProfileParams) (pgconn.CommandTag, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
