name: build and push docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USER_NAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: short sha
        id: short_sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            oatsmoke/warehouse-api:latest
            oatsmoke/warehouse-api:${{steps.short_sha.outputs.SHORT_SHA}}