name: docker build and push

on:
  push:
    branches: [ master ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            hub.docker.com/u/oatsmoke/warehouse-api:latest
            hub.docker.com/u/oatsmoke/warehouse-api:${{github.sha}}jmk
